name: Nix flake check
on:
  pull_request:
  push:
    branches: master


jobs:
  check:
    runs-on: [nix, self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: check flake
        run: nix flake check -L
